import Head from 'next/head';
import { BsFillMoonStarsFill, BsArrowRight } from 'react-icons/bs';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Apocalypse Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='fixed top-0 left-0 w-1/12 h-full backdrop-blur-md bg-darkbgtransp z-50'>
        <nav className='text-white py-40 px-5 gap-12 flex flex-col justify-between h-full align-middle text-xs font-proximaRegular uppercase tracking-widest'>
          <a href="#" className='w-30 h-30'>
            <img src="https://images.squarespace-cdn.com/content/v1/5cce02360cf57d4ffa01a42d/1576460392832-3QJEW5VFO1L3RXRMSI66/BA+Original.png?format=1500w" className='w-1/2 h-auto m-auto border-0 border-black rounded-full object-cover transition-all hover:-translate-y-1 hover:border-4 hover:border-white' alt="" />
          </a>
          <ul className='flex gap-1 items-center justify-center font-proximaBold'>
            <li>
              <a href="#" className='text-4xl p-2 text-white font-apocalypse rounded-md transition-all hover:bg-darkbgtransp hover:text-white'>
                EN
              </a>
            </li>
            <li>
              <a href="#" className='text-4xl p-2 text-white font-apocalypse rounded-md transition-all hover:bg-darkbgtransp hover:text-white'>
                HU
              </a>
            </li>
          </ul>

          <ul className='flex flex-col font-proximaBold text-sm gap-10 items-center'>
            <li>
              <a href="#">
                Homepage
              </a>
            </li>
            <li>
              <a href="#">
                Pricing
              </a>
            </li>
            <li>
              <a href="#">
                Contact
              </a>
            </li>
            <li>
              <a href="#">
                Support
              </a>
            </li>
          </ul>

          <ul className='flex items-center gap-5 justify-center'>
            <li>
              <BsFillMoonStarsFill className='cursor-pointer text-white text-2xl' /></li>
          </ul>
        </nav>
      </header>

      <main className='flex'>
        <aside className='h-auto w-1/12 bg-darkbg'>
        </aside>

        <div className='bg-white w-11/12 overflow-hidden'>
          <section className='relative min-h-screen pt-10 pb-40 m-auto bg-src bg-hero-pattern bg-cover w-full flex'>
            <div className='max-w-6xl m-auto'>
              <h2 className='font-proximaBlack text-8xl mb-5'>GET READY FOR APOCALPYSE</h2>
              <p className='font-proximaRegular mb-10 tracking-wide max-w-2xl text-white drop-shadow-lg'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus adipisci consectetur vitae inventore magni dolorum sequi mollitia quisquam officiis voluptatibus?</p>
              <a href="#" className=' bg-black transition-all inline-block hover:bg-darkbgtransp font-proximaBold text-white px-6 py-5 tracking-widest uppercase text-xl'>Discover</a>
            </div>

            <div className="absolute bottom-0 bg-gradient-to-t from-black left-0 w-full h-50 flex">
              <div className='text-white p-5 px-10 border-b-2 border-red'>
                <p className='mb-8 font-proximaRegular'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius necessitatibus optio quibusdam?</p>
                <a href='#' className='flex font-apocalypse gap-7 text-4xl items-center transition-all hover:text-red'>NASDA JURA <BsArrowRight className='text-2xl' /></a>
              </div>
              <div className='text-white p-5 px-10 border-b-2'>
                <p className='mb-8 font-proximaRegula'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius necessitatibus optio quibusdam?</p>
                <a href='#' className='flex font-apocalypse gap-7 text-4xl items-center transition-all hover:text-red'>NASDA JURA <BsArrowRight className='text-2xl' /></a>
              </div>
              <div className='text-white p-5 px-10 border-b-2'>
                <p className='mb-8 font-proximaRegula'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius necessitatibus optio quibusdam?</p>
                <a href='#' className='flex font-apocalypse gap-7 text-4xl items-center transition-all hover:text-red'>NASDA JURA <BsArrowRight className='text-2xl' /></a>
              </div>
            </div>
          </section>

          <section className='relative m-auto bg-black w-full flex-col pb-10'>
            <h2 className='text-center text-white w-full pt-24 font-apocalypse text-6xl'>START YOUR STORY</h2>
            <p className='text-center text-white font-proximaRegular w-full my-3 mb-28'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, itaque</p>
            <div className="z-10 flex w-full m-auto gap-5 h-full">
              <a href="#" className='px-16 py-24 transition-all hover:-translate-y-2' style={{
                backgroundImage: "url('https://mediafeed.org/wp-content/uploads/2021/08/apocalypse.jpg')",
                backgroundSize: 'cover'
              }}>
                <h4 className='font-proximaBlack text-4xl mb-5 text-white drop-shadow-3xl'>GRAHKAD GURA</h4>
                <p className='font-proximaRegular mb-10 tracking-wide max-w-2xl drop-shadow-2xl text-white'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus adipisci consectetur vitae inventore magni dolorum sequi mollitia quisquam officiis voluptatibus?</p>
                <a href="#" className='transition-all inline-block hover:bg-white hover:text-darkbg hover:border-white font-proximaBold text-white px-6 py-5 border-2 tracking-widest uppercase'>Discover</a>
              </a>

              <a href="#" className='px-16 py-24 transition-all hover:-translate-y-2' style={{
                backgroundImage: "url('https://media.istockphoto.com/id/176657621/photo/background-apocalyptic-scenario.jpg?s=612x612&w=0&k=20&c=u7Z3fBLNk0vx74QPnUao-XL3XRod0Y4HwAYG2egSMYc=')",
                backgroundSize: 'cover'
              }}>
                <h4 className='font-proximaBlack text-4xl mb-5 text-white drop-shadow-3xl'>GRAHKAD GURA</h4>
                <p className='font-proximaRegular mb-10 tracking-wide max-w-2xl drop-shadow-2xl text-white'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus adipisci consectetur vitae inventore magni dolorum sequi mollitia quisquam officiis voluptatibus?</p>
                <a href="#" className='transition-all inline-block hover:bg-white hover:text-darkbg hover:border-white font-proximaBold text-white px-6 py-5 border-2 tracking-widest uppercase'>Discover</a>
              </a>

              <a href="#" className='px-16 py-24 transition-all hover:-translate-y-2' style={{
                backgroundImage: "url('https://media.istockphoto.com/id/931050898/photo/post-apocalypse-destroyed-city-street.jpg?s=612x612&w=0&k=20&c=MO7uYetN4U7I-iMMZPyvLF19_gXzLqwGGIQV4tzniBE=')",
                backgroundSize: 'cover'
              }}>
                <h4 className='font-proximaBlack text-4xl mb-5 text-white drop-shadow-3xl'>GRAHKAD GURA</h4>
                <p className='font-proximaRegular mb-10 tracking-wide max-w-2xl drop-shadow-2xl text-white'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus adipisci consectetur vitae inventore magni dolorum sequi mollitia quisquam officiis voluptatibus?</p>
                <a href="#" className='transition-all inline-block hover:bg-white hover:text-darkbg hover:border-white font-proximaBold text-white px-6 py-5 border-2 tracking-widest uppercase'>Discover</a>
              </a>

              <a href="#" className='px-16 py-24 transition-all hover:-translate-y-2' style={{
                backgroundImage: "url('https://images2.alphacoders.com/102/1024939.jpg')",
                backgroundSize: 'cover'
              }}>
                <h4 className='font-proximaBlack text-4xl mb-5 text-white drop-shadow-3xl'>GRAHKAD GURA</h4>
                <p className='font-proximaRegular mb-10 tracking-wide max-w-2xl drop-shadow-2xl text-white'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus adipisci consectetur vitae inventore magni dolorum sequi mollitia quisquam officiis voluptatibus?</p>
                <a href="#" className='transition-all inline-block hover:bg-white hover:text-darkbg hover:border-white font-proximaBold text-white px-6 py-5 border-2 tracking-widest uppercase'>Discover</a>
              </a>
            </div>
          </section>
        </div>
      </main>
    </div>
  )
}
