import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Something new</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=' bg-purple-500 min-h-screen'>
          <h1 className='text-3xl font-bold underline'>Hey</h1>
        </section>
      </main>
    </div>
  )
}
